#!/usr/bin/env bash

usage() {
    echo "Usage: $0 CLUSTER_NAME SERVER TOKEN"
}

if [[ $# -ne 3 ]]; then
    usage
    exit 1
fi

CLUSTER_NAME=$1
SERVER=$2
TOKEN=$3

kubectl config set-cluster "$CLUSTER_NAME" --server="$SERVER" --insecure-skip-tls-verify=true
kubectl config set-credentials admin@"$CLUSTER_NAME" --token="$TOKEN"
kubectl config set-context "$CLUSTER_NAME"  --cluster="$CLUSTER_NAME" --user=admin@"$CLUSTER_NAME"
kubectl config use-context "$CLUSTER_NAME"

# vim:ft=sh:et:si:ts=4:sts=4:sw=4
